# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 70074d804c370256f35d29d57000898735250979ab14dc024c6f542e659aac57eeb619f975e8b7debaf73e1ef23b30087daab59a93ecfec79918c3097503f0d4

test:
  secret_key_base: e767576cc313f0ca1d20aa4be3c0b61a7366c097bc422cef17fae9043d721cec83cb91fddf56f520e18838b4705d7fc75eda77df1ee5f0a1bdb07946cb3ca3c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
